# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.ssh.insert_key = false
  config.vm.synced_folder '../../.', '/vagrant', type: 'nfs'
  config.vm.synced_folder '~/code/ogs6/ogs', '/home/vagrant/ogs', type: 'nfs'

  config.vm.hostname = "ubuntu1604-ogs"
  config.vm.box = "file://../../builds/ubuntu1604-ogs.box"
  config.vm.network :private_network, ip: "172.16.3.2"

  config.vm.provider :virtualbox do |v|
    v.gui = false
    v.memory = 2048
    v.cpus = 2
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    v.customize ["modifyvm", :id, "--ioapic", "on"]
  end

  config.vm.provision "shell", inline: "echo Hello, World"

end
